version: 2
project_name: forgetool
builds:
  - id: forgetool
    main: .
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - freebsd
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.Version={{.Version}}  # Adjust path if necessary
gomod:
  dir: .
archives:
  - name_template: "{{.ProjectName}}_{{ .Version }}_{{.Os}}_{{.Arch}}"
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^Merge pull request #\d+ from'
release:
  name_template: "{{.ProjectName}}-{{.Tag}}"
  github:
    owner: trueforge-org
    name: forgetool
  extra_files:
    - glob: "forgetool.LICENSE"
  draft: true
  make_latest: false
  mode: append

git:
  ignore_tags:
    - nightly
    - common

universal_binaries:
  - replace: true

report_sizes: true

# sboms:
#   - artifacts: archive
#   - id: source
#     artifacts: source

nfpms:
  - package_name: forgetool
    maintainer: "TrueForge <info@TrueForge.org>"
    homepage: "https://trueforge.org"
    description: "Tool to help bootstrap a Kubernetes cluster"
    license: "BUSL-1.1"
    vendor: TrueForge
    formats: [apk, deb, rpm, termux.deb, archlinux]

aurs:
  - name: "forgetool-bin"
    maintainers:
      - "TrueCharts <info@trueforge.org>"
    homepage: "https://trueforge.org"
    description: "Tool to help bootstrap a Kubernetes cluster"
    license: "BUSL-1.1"
    git_url: "ssh://aur@aur.archlinux.org/forgetool-bin.git"
    skip_upload: auto
    package: |
      # Install binary
      bsdtar -xvf forgetool_${pkgver}_linux_${CARCH}.tar.gz -C "${pkgdir}"
      install -Dm755 "${pkgdir}/forgetool" "${pkgdir}/usr/bin/forgetool"

      # Install license
      install -Dm644 "${pkgdir}/LICENSE" "${pkgdir}/usr/share/licenses/${pkgname}/LICENSE"
