name: forgetool-go-tests
on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - main
    tags:
      - "*"
    paths:
      - 'main.go'
      - 'go.mod'
      - 'go.sum'
      - 'pkg/**'
      - 'cmd/**'
      - ".github/workflows/forgetool.test.yaml"
  #pull_request:
  #  branches:
  #    - main
  #  paths:
  #    - 'main.go'
  #    - 'go.mod'
  #    - 'go.sum'
  #    - 'pkg/**'
  #    - 'cmd/**'
  #    - 'clustertool/**'
  #    - ".github/workflows/clsutertool.test.yaml"
permissions:
  contents: read
jobs:

  check_changes:
    runs-on: ubuntu-latest
    outputs:
      changes_detected: ${{ steps.filter.outputs.changed }}

    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Filter paths
        id: filter
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3
        with:
          list-files: json
          filters: |
            changed:
            - '**'

  build:
    runs-on:
      group: default    
    if: needs.check_changes.outputs.changes_detected == 'true'
    steps:
      - uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6
        with:
          go-version: stable
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - run:  |
          go build -o /usr/local/bin/forgetool
          go test -v ./... -race -covermode=atomic
          forgetool-dev