name: "Chore: Go mod tidy"

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  go-mod-tidy:
    runs-on: ubuntu-latest
    name: "Chore: Go mod tidy"
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
        ## DISABLED by Boemeltrein 
        # with:
        #   token: ${{ secrets.OR_PAT }}
        #   fetch-depth: 1

      - uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6
        with:
          go-version: stable
          cache: true
          cache-dependency-path: |
            **/go.mod
            **/go.sum

      - name: Ensure Go Mod Tidy
        run:  |
          go mod tidy

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8
        with:
          branch: chore/go-mod-tidy
          delete-branch: true
          commit-message: "chore(go): go mod tidy"
          title: "chore(go): go mod tidy"
          body: |
            Automated `go mod tidy` run.

            - Triggered by: `${{ github.event_name }}`
            - Workflow: `${{ github.workflow }}`
          labels: |
            chore
            go
