name: "Chore: mod-tidy and fmt"

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  go-mod-tidy:
    runs-on: ubuntu-latest
    name: "Chore: Go mod tidy"
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
          fetch-depth: 1

      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          go-version: stable
          cache: true
          cache-dependency-path: |
            **/go.mod
            **/go.sum

      - name: Ensure Go Mod Tidy
        run:  |
          go mod tidy

      - name: Ensure formatting
        uses: Jerome1337/gofmt-action@d5eabd189843f1d568286a54578159978b7c0fb1 # v1.0.5

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8
        with:
          branch: chore/go-mod-tidy
          delete-branch: true
          commit-message: "chore(go): go mod tidy"
          title: "chore(go): go mod tidy"
          body: |
            Automated `go mod tidy` run.

            - Triggered by: `${{ github.event_name }}`
            - Workflow: `${{ github.workflow }}`
          labels: |
            chore
            go
