name: "Chore: mod-tidy and fmt"

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  go-mod-tidy:
    runs-on: ubuntu-latest
    name: "Chore: Go mod tidy"
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
          fetch-depth: 1

      - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6
        with:
          go-version: stable
          cache: true
          cache-dependency-path: |
            **/go.mod
            **/go.sum

      - name: Ensure Go Mod Tidy
        run:  |
          go mod tidy

      - name: Ensure formatting
        uses: Jerome1337/gofmt-action@d5eabd189843f1d568286a54578159978b7c0fb1 # v1.0.5

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8
        with:
          branch: chore/go-mod-tidy
          delete-branch: true
          commit-message: "chore(go): go mod tidy"
          title: "chore(go): go mod tidy"
          body: |
            Automated `go mod tidy` run.

            - Triggered by: `${{ github.event_name }}`
            - Workflow: `${{ github.workflow }}`
          labels: |
            chore
            go
